// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | HeroImageOverlaySlice
  | LogoGridSlice
  | IntroTextFeatureGraphicSlice
  | FormContactSlice
  | MediaGridIntroSlice
  | SolutionsGridSlice
  | TestimonialCardListSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type SolucionDocumentDataSlicesSlice =
  | FormContactSlice
  | BrandTextColumnsSlice
  | FeatureHighlightsGridSlice;

/**
 * Content for Solución documents
 */
interface SolucionDocumentData {
  /**
   * Slice Zone field in *Solución*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: solucion.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SolucionDocumentDataSlicesSlice>; /**
   * Meta Title field in *Solución*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: solucion.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Solución*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: solucion.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Solución*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solucion.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Solución document from Prismic
 *
 * - **API ID**: `solucion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SolucionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SolucionDocumentData>,
    "solucion",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | SolucionDocument;

/**
 * Item in *BrandTextColumns → Logo with Two Text Columns → Primary → Columnas*
 */
export interface BrandTextColumnsSliceLogoTwoTextColumnsPrimaryTextColumnsItem {
  /**
   * Párrafo field in *BrandTextColumns → Logo with Two Text Columns → Primary → Columnas*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_text_columns.logo_two_text_columns.primary.text_columns[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *BrandTextColumns → Logo with Two Text Columns → Primary*
 */
export interface BrandTextColumnsSliceLogoTwoTextColumnsPrimary {
  /**
   * Logo field in *BrandTextColumns → Logo with Two Text Columns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_text_columns.logo_two_text_columns.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Columnas field in *BrandTextColumns → Logo with Two Text Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_text_columns.logo_two_text_columns.primary.text_columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  text_columns: prismic.GroupField<
    Simplify<BrandTextColumnsSliceLogoTwoTextColumnsPrimaryTextColumnsItem>
  >;
}

/**
 * Logo with Two Text Columns variation for BrandTextColumns Slice
 *
 * - **API ID**: `logo_two_text_columns`
 * - **Description**: Displays a logo or brand mark on the left and two columns of descriptive text to the right, supporting short guarantee or informational statements.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandTextColumnsSliceLogoTwoTextColumns =
  prismic.SharedSliceVariation<
    "logo_two_text_columns",
    Simplify<BrandTextColumnsSliceLogoTwoTextColumnsPrimary>,
    never
  >;

/**
 * Slice variation for *BrandTextColumns*
 */
type BrandTextColumnsSliceVariation = BrandTextColumnsSliceLogoTwoTextColumns;

/**
 * BrandTextColumns Shared Slice
 *
 * - **API ID**: `brand_text_columns`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandTextColumnsSlice = prismic.SharedSlice<
  "brand_text_columns",
  BrandTextColumnsSliceVariation
>;

/**
 * Item in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Características*
 */
export interface FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeaturesItem {
  /**
   * Icono field in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Características*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Título field in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Características*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.features[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Item in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Información del servicio*
 */
export interface FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeatureDescriptionsItem {
  /**
   * Párrafo field in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Información del servicio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.feature_descriptions[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;
}

/**
 * Item in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Galería*
 */
export interface FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryImagenesItem {
  /**
   * Imagen field in *FeatureHighlightsGrid → Three Columns with Intro → Primary → Galería*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.imagenes[].imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;
}

/**
 * Primary content in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
 */
export interface FeatureHighlightsGridSliceThreeColumnsWithIntroPrimary {
  /**
   * Título del servicio field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Subtítulo field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Descripción del servicio field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Imagen principal field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.imagen_principal
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen_principal: prismic.ImageField<never>;

  /**
   * Características field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeaturesItem>
  >;

  /**
   * Información del servicio field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.feature_descriptions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_descriptions: prismic.GroupField<
    Simplify<FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeatureDescriptionsItem>
  >;

  /**
   * Galería field in *FeatureHighlightsGrid → Three Columns with Intro → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlights_grid.three_columns_with_intro.primary.imagenes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  imagenes: prismic.GroupField<
    Simplify<FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryImagenesItem>
  >;
}

/**
 * Three Columns with Intro variation for FeatureHighlightsGrid Slice
 *
 * - **API ID**: `three_columns_with_intro`
 * - **Description**: Displays three feature columns with icons, headings, and images under an introductory section.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureHighlightsGridSliceThreeColumnsWithIntro =
  prismic.SharedSliceVariation<
    "three_columns_with_intro",
    Simplify<FeatureHighlightsGridSliceThreeColumnsWithIntroPrimary>,
    never
  >;

/**
 * Slice variation for *FeatureHighlightsGrid*
 */
type FeatureHighlightsGridSliceVariation =
  FeatureHighlightsGridSliceThreeColumnsWithIntro;

/**
 * FeatureHighlightsGrid Shared Slice
 *
 * - **API ID**: `feature_highlights_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureHighlightsGridSlice = prismic.SharedSlice<
  "feature_highlights_grid",
  FeatureHighlightsGridSliceVariation
>;

/**
 * Primary content in *FormContact → Default → Primary*
 */
export interface FormContactSliceDefaultPrimary {
  /**
   * Name Field Label field in *FormContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_contact.default.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField;

  /**
   * Email Field Label field in *FormContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_contact.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Message Field Label field in *FormContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_contact.default.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField;

  /**
   * Submit Button Text field in *FormContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_contact.default.primary.submit_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_text: prismic.KeyTextField;
}

/**
 * Default variation for FormContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard contact form layout with name, email, message fields, and a submit button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormContact*
 */
type FormContactSliceVariation = FormContactSliceDefault;

/**
 * FormContact Shared Slice
 *
 * - **API ID**: `form_contact`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormContactSlice = prismic.SharedSlice<
  "form_contact",
  FormContactSliceVariation
>;

/**
 * Primary content in *HeroImageOverlay → Centered Headline with Image → Primary*
 */
export interface HeroImageOverlaySliceCenteredHeadlineWithImagePrimary {
  /**
   * Imagen de fondo field in *HeroImageOverlay → Centered Headline with Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_overlay.centered_headline_with_image.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Texto principal field in *HeroImageOverlay → Centered Headline with Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_overlay.centered_headline_with_image.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;
}

/**
 * Centered Headline with Image variation for HeroImageOverlay Slice
 *
 * - **API ID**: `centered_headline_with_image`
 * - **Description**: Hero with large central headline text overlay and background image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageOverlaySliceCenteredHeadlineWithImage =
  prismic.SharedSliceVariation<
    "centered_headline_with_image",
    Simplify<HeroImageOverlaySliceCenteredHeadlineWithImagePrimary>,
    never
  >;

/**
 * Slice variation for *HeroImageOverlay*
 */
type HeroImageOverlaySliceVariation =
  HeroImageOverlaySliceCenteredHeadlineWithImage;

/**
 * HeroImageOverlay Shared Slice
 *
 * - **API ID**: `hero_image_overlay`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageOverlaySlice = prismic.SharedSlice<
  "hero_image_overlay",
  HeroImageOverlaySliceVariation
>;

/**
 * Primary content in *IntroTextFeatureGraphic → Default → Primary*
 */
export interface IntroTextFeatureGraphicSliceDefaultPrimary {
  /**
   * Titulo field in *IntroTextFeatureGraphic → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_feature_graphic.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descripción field in *IntroTextFeatureGraphic → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_feature_graphic.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for IntroTextFeatureGraphic Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays heading, description, and a single feature graphic with flexible layout.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextFeatureGraphicSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroTextFeatureGraphicSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroTextFeatureGraphic*
 */
type IntroTextFeatureGraphicSliceVariation =
  IntroTextFeatureGraphicSliceDefault;

/**
 * IntroTextFeatureGraphic Shared Slice
 *
 * - **API ID**: `intro_text_feature_graphic`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextFeatureGraphicSlice = prismic.SharedSlice<
  "intro_text_feature_graphic",
  IntroTextFeatureGraphicSliceVariation
>;

/**
 * Item in *LogoGrid → With Title → Primary → Logos*
 */
export interface LogoGridSliceWithTitlePrimaryLogosItem {
  /**
   * Logo del cliente field in *LogoGrid → With Title → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_grid.with_title.primary.logos[].logo_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoGrid → With Title → Primary*
 */
export interface LogoGridSliceWithTitlePrimary {
  /**
   * Titulo field in *LogoGrid → With Title → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_grid.with_title.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Logos field in *LogoGrid → With Title → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_grid.with_title.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<LogoGridSliceWithTitlePrimaryLogosItem>>;
}

/**
 * With Title variation for LogoGrid Slice
 *
 * - **API ID**: `with_title`
 * - **Description**: Includes a section title and a group of logo items.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSliceWithTitle = prismic.SharedSliceVariation<
  "with_title",
  Simplify<LogoGridSliceWithTitlePrimary>,
  never
>;

/**
 * Slice variation for *LogoGrid*
 */
type LogoGridSliceVariation = LogoGridSliceWithTitle;

/**
 * LogoGrid Shared Slice
 *
 * - **API ID**: `logo_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoGridSlice = prismic.SharedSlice<
  "logo_grid",
  LogoGridSliceVariation
>;

/**
 * Item in *MediaContentGrid → Image Grid With Text Columns → Primary → Media Items*
 */
export interface MediaContentGridSliceImageGridColumnsPrimaryMediaItemsItem {
  /**
   * Image field in *MediaContentGrid → Image Grid With Text Columns → Primary → Media Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_content_grid.image_grid_columns.primary.media_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *MediaContentGrid → Image Grid With Text Columns → Primary → Content Columns*
 */
export interface MediaContentGridSliceImageGridColumnsPrimaryContentColumnsItem {
  /**
   * Body field in *MediaContentGrid → Image Grid With Text Columns → Primary → Content Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_content_grid.image_grid_columns.primary.content_columns[].column_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  column_body: prismic.RichTextField;
}

/**
 * Primary content in *MediaContentGrid → Image Grid With Text Columns → Primary*
 */
export interface MediaContentGridSliceImageGridColumnsPrimary {
  /**
   * Media Items field in *MediaContentGrid → Image Grid With Text Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_content_grid.image_grid_columns.primary.media_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  media_items: prismic.GroupField<
    Simplify<MediaContentGridSliceImageGridColumnsPrimaryMediaItemsItem>
  >;

  /**
   * Content Columns field in *MediaContentGrid → Image Grid With Text Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_content_grid.image_grid_columns.primary.content_columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  content_columns: prismic.GroupField<
    Simplify<MediaContentGridSliceImageGridColumnsPrimaryContentColumnsItem>
  >;
}

/**
 * Image Grid With Text Columns variation for MediaContentGrid Slice
 *
 * - **API ID**: `image_grid_columns`
 * - **Description**: Displays a grid of images on top with two or more columns of text content below, suitable for layouts mixing visual media and detailed descriptions.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaContentGridSliceImageGridColumns =
  prismic.SharedSliceVariation<
    "image_grid_columns",
    Simplify<MediaContentGridSliceImageGridColumnsPrimary>,
    never
  >;

/**
 * Slice variation for *MediaContentGrid*
 */
type MediaContentGridSliceVariation = MediaContentGridSliceImageGridColumns;

/**
 * MediaContentGrid Shared Slice
 *
 * - **API ID**: `media_content_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaContentGridSlice = prismic.SharedSlice<
  "media_content_grid",
  MediaContentGridSliceVariation
>;

/**
 * Item in *MediaGridIntro → Headline with Image Grid → Primary → Media Items*
 */
export interface MediaGridIntroSliceHeadlineImageGridPrimaryMediaItemsItem {
  /**
   * Imagen field in *MediaGridIntro → Headline with Image Grid → Primary → Media Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_grid_intro.headline_image_grid.primary.media_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *MediaGridIntro → Headline with Image Grid → Primary*
 */
export interface MediaGridIntroSliceHeadlineImageGridPrimary {
  /**
   * Titulo field in *MediaGridIntro → Headline with Image Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_grid_intro.headline_image_grid.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Media Items field in *MediaGridIntro → Headline with Image Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_grid_intro.headline_image_grid.primary.media_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  media_items: prismic.GroupField<
    Simplify<MediaGridIntroSliceHeadlineImageGridPrimaryMediaItemsItem>
  >;
}

/**
 * Headline with Image Grid variation for MediaGridIntro Slice
 *
 * - **API ID**: `headline_image_grid`
 * - **Description**: Displays a prominent headline next to a grid of images, ideal for highlighting clients or partners visually.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGridIntroSliceHeadlineImageGrid = prismic.SharedSliceVariation<
  "headline_image_grid",
  Simplify<MediaGridIntroSliceHeadlineImageGridPrimary>,
  never
>;

/**
 * Slice variation for *MediaGridIntro*
 */
type MediaGridIntroSliceVariation = MediaGridIntroSliceHeadlineImageGrid;

/**
 * MediaGridIntro Shared Slice
 *
 * - **API ID**: `media_grid_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGridIntroSlice = prismic.SharedSlice<
  "media_grid_intro",
  MediaGridIntroSliceVariation
>;

/**
 * Item in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
 */
export interface SolutionsGridSliceFeaturedItemGridPrimarySolutionsItem {
  /**
   * Icono field in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Titulo field in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descripción field in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Enlace field in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Destacado field in *SolutionsGrid → Featured Item Grid → Primary → Soluciones*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[].featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Primary content in *SolutionsGrid → Featured Item Grid → Primary*
 */
export interface SolutionsGridSliceFeaturedItemGridPrimary {
  /**
   * Titulo field in *SolutionsGrid → Featured Item Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Soluciones field in *SolutionsGrid → Featured Item Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_grid.featured_item_grid.primary.solutions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  solutions: prismic.GroupField<
    Simplify<SolutionsGridSliceFeaturedItemGridPrimarySolutionsItem>
  >;
}

/**
 * Featured Item Grid variation for SolutionsGrid Slice
 *
 * - **API ID**: `featured_item_grid`
 * - **Description**: A grid display of items where one is featured/highlighted, including icon, title, optional description, and link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionsGridSliceFeaturedItemGrid = prismic.SharedSliceVariation<
  "featured_item_grid",
  Simplify<SolutionsGridSliceFeaturedItemGridPrimary>,
  never
>;

/**
 * Slice variation for *SolutionsGrid*
 */
type SolutionsGridSliceVariation = SolutionsGridSliceFeaturedItemGrid;

/**
 * SolutionsGrid Shared Slice
 *
 * - **API ID**: `solutions_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionsGridSlice = prismic.SharedSlice<
  "solutions_grid",
  SolutionsGridSliceVariation
>;

/**
 * Item in *TestimonialCardList → Default → Primary → Testimoniales*
 */
export interface TestimonialCardListSliceDefaultPrimaryTestimonialsItem {
  /**
   * Avatar field in *TestimonialCardList → Default → Primary → Testimoniales*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.testimonials[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Nombre del autor field in *TestimonialCardList → Default → Primary → Testimoniales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.testimonials[].author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Rating field in *TestimonialCardList → Default → Primary → Testimoniales*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;

  /**
   * Texto testimonial field in *TestimonialCardList → Default → Primary → Testimoniales*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.testimonials[].testimonial_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_text: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialCardList → Default → Primary*
 */
export interface TestimonialCardListSliceDefaultPrimary {
  /**
   * Titulo field in *TestimonialCardList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Testimoniales field in *TestimonialCardList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card_list.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialCardListSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for TestimonialCardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard testimonial card list with image, rating, author, and testimonial text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialCardListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialCardListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialCardList*
 */
type TestimonialCardListSliceVariation = TestimonialCardListSliceDefault;

/**
 * TestimonialCardList Shared Slice
 *
 * - **API ID**: `testimonial_card_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialCardListSlice = prismic.SharedSlice<
  "testimonial_card_list",
  TestimonialCardListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SolucionDocument,
      SolucionDocumentData,
      SolucionDocumentDataSlicesSlice,
      AllDocumentTypes,
      BrandTextColumnsSlice,
      BrandTextColumnsSliceLogoTwoTextColumnsPrimaryTextColumnsItem,
      BrandTextColumnsSliceLogoTwoTextColumnsPrimary,
      BrandTextColumnsSliceVariation,
      BrandTextColumnsSliceLogoTwoTextColumns,
      FeatureHighlightsGridSlice,
      FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeaturesItem,
      FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryFeatureDescriptionsItem,
      FeatureHighlightsGridSliceThreeColumnsWithIntroPrimaryImagenesItem,
      FeatureHighlightsGridSliceThreeColumnsWithIntroPrimary,
      FeatureHighlightsGridSliceVariation,
      FeatureHighlightsGridSliceThreeColumnsWithIntro,
      FormContactSlice,
      FormContactSliceDefaultPrimary,
      FormContactSliceVariation,
      FormContactSliceDefault,
      HeroImageOverlaySlice,
      HeroImageOverlaySliceCenteredHeadlineWithImagePrimary,
      HeroImageOverlaySliceVariation,
      HeroImageOverlaySliceCenteredHeadlineWithImage,
      IntroTextFeatureGraphicSlice,
      IntroTextFeatureGraphicSliceDefaultPrimary,
      IntroTextFeatureGraphicSliceVariation,
      IntroTextFeatureGraphicSliceDefault,
      LogoGridSlice,
      LogoGridSliceWithTitlePrimaryLogosItem,
      LogoGridSliceWithTitlePrimary,
      LogoGridSliceVariation,
      LogoGridSliceWithTitle,
      MediaContentGridSlice,
      MediaContentGridSliceImageGridColumnsPrimaryMediaItemsItem,
      MediaContentGridSliceImageGridColumnsPrimaryContentColumnsItem,
      MediaContentGridSliceImageGridColumnsPrimary,
      MediaContentGridSliceVariation,
      MediaContentGridSliceImageGridColumns,
      MediaGridIntroSlice,
      MediaGridIntroSliceHeadlineImageGridPrimaryMediaItemsItem,
      MediaGridIntroSliceHeadlineImageGridPrimary,
      MediaGridIntroSliceVariation,
      MediaGridIntroSliceHeadlineImageGrid,
      SolutionsGridSlice,
      SolutionsGridSliceFeaturedItemGridPrimarySolutionsItem,
      SolutionsGridSliceFeaturedItemGridPrimary,
      SolutionsGridSliceVariation,
      SolutionsGridSliceFeaturedItemGrid,
      TestimonialCardListSlice,
      TestimonialCardListSliceDefaultPrimaryTestimonialsItem,
      TestimonialCardListSliceDefaultPrimary,
      TestimonialCardListSliceVariation,
      TestimonialCardListSliceDefault,
    };
  }
}
