// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  form_contact: dynamic(() => import("./FormContact")),
  hero_image_overlay: dynamic(() => import("./HeroImageOverlay")),
  intro_text_feature_graphic: dynamic(
    () => import("./IntroTextFeatureGraphic"),
  ),
  logo_grid: dynamic(() => import("./LogoGrid")),
  media_grid_intro: dynamic(() => import("./MediaGridIntro")),
  solutions_grid: dynamic(() => import("./SolutionsGrid")),
  testimonial_card_list: dynamic(() => import("./TestimonialCardList")),
};
